# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171205_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='model_b',
            field=models.ManyToManyField(blank=True, to='app.ModelB'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='model_c',
            field=models.ManyToManyField(blank=True, to='app.ModelC'),
        ),
    ]
